### PR TITLE
Added France mirror on mirrors.yaml

### PR DESCRIPTION
**Pull request by hisuiki**
- I added a new tier 1 mirror (1hr sync) on France

### CODE REVIEW

**Comment by classabbyamp** [comment]
> Tier 1 mirrors are maintained by the Void Linux Infrastructure Team.

this is not true of this mirror so it should be tier 2

**Comment by Powerm1nt** [comment]
> > Tier 1 mirrors are maintained by the Void Linux Infrastructure Team.
> 
> this is not true of this mirror so it should be tier 2

Let me fix that one sec

**Comment by Powerm1nt** [comment]
i changed to tier 2

**Comment by Powerm1nt** [comment]
I updated location info

**Comment by classabbyamp** [comment]
why close this?

**Pull request closed without merging**
