### PR TITLE
Add a new mirror

### PR DESCRIPTION
**Pull request by cicku**
Love to help.

### CODE REVIEW

**Comment by Powerm1nt** [comment]
UP

**Comment by Vaelatern** [comment]
Apparently CloudFlare TOS says something negative about binary artifacts (aka packages)?

**Comment by cicku** [comment]
I work there :D

**Comment by Vaelatern** [comment]
Do you work in the TOS enforcement division?

**Comment by cicku** [comment]
It does not matter. I have been providing the mirror service for quite a while in this way (PB level of data transfer every month). If we have determined the usage is unbearable, then you won't see me here.

**Comment by classabbyamp** [comment]
I'd rather have the one cdn mirror than a bunch of regional mirrors. shouldn't the cdn use the closest region automatically?

**Comment by cicku** [comment]
Definitely. I can go back to the initial setup if you want, no issues with it.

My only concern is how you load balance the traffic between fastly and us, if there is no issue then I will revert.

**Comment by classabbyamp** [comment]
users manually select the mirror they want to use. there is no load balancing

**Comment by Vaelatern** [comment]
We will merge the 1 endpoint approach

**Comment by Vaelatern** [comment]
Alright, please squash into 1 commit, message:

```
mirrors.yaml: Add cicku's mirror
```

or something to that effect

Or I can do it for you and push.

**Pull request merged**
